//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogInForm {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangPack_us_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangPack_us_EN() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogInForm.LangPack_us_EN", typeof(LangPack_us_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Configuration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONFIG {
            get {
                return ResourceManager.GetString("CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DEL_QUE {
            get {
                return ResourceManager.GetString("DEL_QUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deletion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid input format.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string INVALID_VALUE_TEXT {
            get {
                return ResourceManager.GetString("INVALID_VALUE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LANG {
            get {
                return ResourceManager.GetString("LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chinese과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LANG_CHS {
            get {
                return ResourceManager.GetString("LANG_CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LANG_EN {
            get {
                return ResourceManager.GetString("LANG_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LANG_JP {
            get {
                return ResourceManager.GetString("LANG_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korean과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LANG_KR {
            get {
                return ResourceManager.GetString("LANG_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration file, or set the server does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOT_CONF {
            get {
                return ResourceManager.GetString("NOT_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plant Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLANT {
            get {
                return ResourceManager.GetString("PLANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The plant does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLANT_ERR {
            get {
                return ResourceManager.GetString("PLANT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is required.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string REQUIRED_TEXT {
            get {
                return ResourceManager.GetString("REQUIRED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server IP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SERVER_IP {
            get {
                return ResourceManager.GetString("SERVER_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SERVER_NAME {
            get {
                return ResourceManager.GetString("SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SERVER_NUM {
            get {
                return ResourceManager.GetString("SERVER_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SERVER_PORT {
            get {
                return ResourceManager.GetString("SERVER_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access to the server settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SET_CONN {
            get {
                return ResourceManager.GetString("SET_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SKIN {
            get {
                return ResourceManager.GetString("SKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown error, can not access.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UNKNOWN_ERR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERR", resourceCulture);
            }
        }
    }
}
