//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogInForm {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangPack_ko_KR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangPack_ko_KR() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogInForm.LangPack_ko_KR", typeof(LangPack_ko_KR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   환경설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CONFIG {
            get {
                return ResourceManager.GetString("CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터베이스명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DATABASE_NAME {
            get {
                return ResourceManager.GetString("DATABASE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정말 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DEL_QUE {
            get {
                return ResourceManager.GetString("DEL_QUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력 형식이 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string INVALID_VALUE_TEXT {
            get {
                return ResourceManager.GetString("INVALID_VALUE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LANG {
            get {
                return ResourceManager.GetString("LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중국어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LANG_CHS {
            get {
                return ResourceManager.GetString("LANG_CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LANG_EN {
            get {
                return ResourceManager.GetString("LANG_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일본어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LANG_JP {
            get {
                return ResourceManager.GetString("LANG_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한국어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LANG_KR {
            get {
                return ResourceManager.GetString("LANG_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   환경설정 파일 또는 접속서버로 설정된 서버가 존재하지않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NOT_CONF {
            get {
                return ResourceManager.GetString("NOT_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사업장 코드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLANT {
            get {
                return ResourceManager.GetString("PLANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사업장 정보가 존재 하지않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLANT_ERR {
            get {
                return ResourceManager.GetString("PLANT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필수 항목입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string REQUIRED_TEXT {
            get {
                return ResourceManager.GetString("REQUIRED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 아이피과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SERVER_IP {
            get {
                return ResourceManager.GetString("SERVER_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SERVER_NAME {
            get {
                return ResourceManager.GetString("SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SERVER_NUM {
            get {
                return ResourceManager.GetString("SERVER_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 포트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SERVER_PORT {
            get {
                return ResourceManager.GetString("SERVER_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   접속서버로 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SET_CONN {
            get {
                return ResourceManager.GetString("SET_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SKIN {
            get {
                return ResourceManager.GetString("SKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알수없는 오류로 접속할수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UNKNOWN_ERR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERR", resourceCulture);
            }
        }
    }
}
